INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('1', 'Daxue Jiadao', 'Wild Laocong Shuixian', '2017', 'Oolong', 'Wuyi', 'Shui Xian','0.96', '16');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('2', 'One River Tea', 'Longjing #108 | Mingqian Dragonwell Private Order', '2024', 'White', 'Hangzhou', 'Longjing #108','2', '9');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('3', 'Daxue Jiadao', 'Yongchun Shuixian Kaishan', '2023', 'Oolong', 'Yongchun', 'Shui Xian','1.51', '50');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('4', 'One River Tea', 'Silver Needle', '2024', 'White', 'Fuding', 'Baihao','1.20', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('5', 'Unknown', 'Dayi Golden TAE', '2011', 'Puer', 'Aged Sheng', 'Blend','2.50', '30');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('6', 'Teas We Like', 'Biyun Hao Zhengjialiangzi', '2011', 'Puer', 'Aged Sheng', 'Mahei, Yiwu','1.19', '20');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('7', 'Daxue Jiadao', 'Yongchun Shuixian Annual', '2023', 'Oolong', 'Yongchun', 'Shui Xian','0.77', '50');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('8', 'Daxue Jiadao', 'Yongchun Laocong Shuixian Bainian', '2022', 'Oolong', 'Yongchun', 'Shui Xian','1.26', '8');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('9', 'Zoeys Teas', 'Wudong Old Tree Aofuhou', '0', 'Oolong', 'Fenghuang', 'Ao Fu Hou','1.32', '50');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('10', 'Daxue Jiadao', 'Yongchun Fo Shou Kaishan', '2023', 'Oolong', 'Yongchun', 'Fo Shou','1.47', '50');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('11', 'Daxue Jiadao', 'Yongchun Fo Shou Annual', '2023', 'Oolong', 'Yongchun', 'Fo Shou','0.77', '50');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('12', 'Zoeys Teas', 'Mo Li Xiang', '0', 'Oolong', 'Fenghuang', 'Mo Li Xiang','1', '8');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('13', 'Zoeys Teas', 'Real Zheng Yan Hui Yuan Keng Pure Da Hong Pao', '0', 'Oolong', 'Wuyi', 'Blend','1', '8');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('14', 'Old Ways Tea', 'Niu Rou Huangpian', '2023', 'Oolong', 'Wuyi', 'Rou Gui','0.25', '50');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('15', 'Zoeys Teas', 'Ping Keng Tou Yashi Xiang', '0', 'Oolong', 'Fenghuang', 'Yashi Xiang','0.70', '60');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('16', 'One River Tea', 'King Peony', '2024', 'White', 'Fujian', 'Baihao','0.40', '50');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('17', 'Bitterleaf', 'Duck Tale Yashi Xiang', '2023', 'Oolong', 'Fenghuang', 'Yashi Xiang','0.82', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('18', 'TShop', 'Boseong Sejak', '2024', 'Green', 'Boseong', 'NULL','1.75', '5');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('19', 'Teas We Like', 'Chen Yuan Hao Shanzhong Chuanqi', '2005', 'Puer', 'Aged Sheng', 'Gushu Blend','1.74', '20');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('20', 'Song Tea', 'Nantou Dark Sequel', '2023', 'Oolong', 'Hongshui', 'Qing Xin','0.53', '10');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('21', 'Floating Leaves', 'Jade Peak High Montain', '2024', 'Oolong', 'Taiwanese', 'Qing Xin','0.52', '30');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('22', 'Floating Leaves', 'Dong Ding Trad. A', '2024', 'Oolong', 'Dong Ding', 'Qing Xin','0.41', '60');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('23', 'Floating Leaves', 'Farmers Choice Baozhong', '2023', 'Oolong', 'Baozhong', 'Man Zhong','0.35', '60');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('24', 'Old Ways Tea', 'Laocong Shuixian', '2022', 'Oolong', 'Wuyi', 'Shui Xian','0.67', '64');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('25', 'Old Ways Tea', 'Spring Single Cultivar Da Hong Pao', '2021', 'Oolong', 'Wuyi', 'Qi Dan','0.67', '8');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('26', 'Old Ways Tea', 'Bei Dou', '2022', 'Oolong', 'Wuyi', 'Bei Dou','0.33', '40');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('27', 'Daxue Jiadao', 'Guoxiang Rougui', '2022', 'Oolong', 'Wuyi', 'Rou Gui','0.40', '8');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('28', 'Ryuouen', 'Top Shelf Hatsugana Matcha', '2024', 'Green', 'Matcha', 'Blend','1', '20');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('29', 'Floating Leaves', 'High Mountain Diva', '2024', 'Oolong', 'Taiwanese', 'Qing Xin','0.45', '60');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('30', 'Floating Leaves', 'Competition Baozhong', '2024', 'Oolong', 'Baozhong', 'Qing Xin','0.45', '30');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('31', 'Ippodo', 'Kyogoko no Mukashi', '2024', 'Green', 'Matcha', 'Blend','0.59', '20');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('32', 'Ryuouen', 'Saiko', '2024', 'Green', 'Sencha', 'Blend','0.33', '50');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('33', 'Floating Leaves', 'Charcoal Roast Dong Ding', '2024', 'Oolong', 'Dong Ding', 'Ruan Zhi','0.65', '30');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('34', 'Daxue Jiadao', 'Yongchun Fo Shou Trad', '2022', 'Oolong', 'Wuyi', 'Fo Shou','0.77', '8');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('35', 'Teas We Like', 'Red Ribbon', '2001', 'Puer', 'Aged Sheng', 'Blend','0.53', '15');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('36', 'Ketlee', 'First Flush Darjeeling', '2023', 'Black', 'Indian', 'Darjeeling','0.32', '8');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('37', 'Daxue Jiadao', 'Baiyun Rougui', '2022', 'Oolong', 'Wuyi', 'Rou Gui','0.70', '8');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('38', 'Old Ways Tea', 'Light Roast Da Hong Pao', '2024', 'Oolong', 'Wuyi', 'Bei Dou','0.3', '40');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('39', 'Old Ways Tea', 'First Roast Shui Xian', '2023', 'Oolong', 'Wuyi', 'Shui Xian','0.25', '40');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('40', 'Old Ways Tea', 'Second Roast Shui Xian', '2023', 'Oolong', 'Wuyi', 'Shui Xian','0.25', '40');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('41', 'Old Ways Tea', 'Zhangping Shui Xian', '2022', 'Oolong', 'Wuyi', 'Shui Xian','0.22', '8');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('42', 'Bitterleaf', 'Praise Bee Milan Xiang', '2023', 'Oolong', 'Fenghuang', 'Milan Xiang','0.90', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('43', 'Mountain Stream Teas', 'Sanxia Green', '2023', 'Green', 'Taiwanese', 'Sanxia','0.50', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('44', 'Viet Sun', 'Lai Chau Deep Forest Green', '2024', 'Green', 'Vietnamese', 'NSV','0.23', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('45', 'Viet Sun', 'Mong Rong Ya Bao', '2023', 'White', 'Vietnamese', 'Ya Bao','0.25', '8');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('46', 'One River Tea', 'Mingqian Longjing', '2024', 'Green', 'Longjing', 'NULL','0.52', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('47', 'Puerh Junky', 'MKRS ""Creme Florale""', '2011', 'Puer', 'Aged Sheng', 'NULL','0.22', '30');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('48', 'White2Tea', 'Loon-call in the Dark', '2022', 'Puer', 'Shou', 'NULL','0.45', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('49', 'Thes du Japon', 'Kawane, Moto-Fujikawa Shizu-7132', '2023', 'Green', 'Sencha', 'Shizu-7132','0.20', '100');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('50', 'Viet Sun', 'Ha Giang Black', '2024', 'Black', 'Vietnamese', 'NULL','0.19', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('51', 'Morning Crane', 'Kim Jeong Yeol Chungiljem Sejak', '2024', 'Green', 'Korean', 'Sejak','0.75', '15');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('52', 'Viet Sun', 'Pu Ta Leng White', '2023', 'White', 'Vietnamese', 'NSV','0.28', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('53', 'Thes du Japon', 'Fuji-Kaori', '2023', 'Black', 'Wakocha', 'Fuji-Kaori','0.25', '8');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('54', 'Old Ways Tea', 'Tong Mu Charcoal Roast', '2024', 'Black', 'Wuyi', 'Xiao Zhong','0.32', '50');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('55', 'Old Ways Tea', 'Lan Shan Xiao Zhong', '2024', 'Black', 'Wuyi', 'Xiao Zhong','0.32', '40');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('56', 'Old Ways Tea', 'Shui Di Xiang Xiao Zhong', '2024', 'Black', 'Wuyi', 'Xiao Zhong','0.32', '40');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('57', 'Teas We Like', 'Xiaguan Jiaji', '2004', 'Puer', 'Aged Sheng', 'NULL','0.22', '15');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('58', 'Zoeys Teas', 'Traditional Charcoal Roast Tie Guan Yin', '0', 'Oolong', 'Anxi', 'Tie Guan Yin','0.50', '50');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('59', 'Viet Sun', 'Cao Bo White', '2024', 'White', 'Vietnamese', 'NULL','0.14', '12');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('60', 'Ryuouen', 'Asahi', '2024', 'Green', 'Sencha', 'Blend','0.20', '5');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('61', 'Viet Sun', 'Thai Nguyen Fish Hook Green', '2023', 'Green', 'Vietnamese', 'NULL','0.10', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('62', 'Old Ways Tea', 'Aged Da Hong Pao', '2015', 'Oolong', 'Wuyi', 'Bei Dou','0.28', '40');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('63', 'Old Ways Tea', 'Qian Li Xiang', '2023', 'Oolong', 'Wuyi', 'Qian Li Xiang','0.22', '8');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('64', 'Floating Leaves', 'Smooth Water Baozhong', '2024', 'Oolong', 'Taiwanese', 'Qing Xin','0.35', '60');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('65', 'Floating Leaves', 'Sweet Cream Alishan High Mountain', '2024', 'Oolong', 'Taiwanese', 'Qing Xin','0.45', '30');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('66', 'Yee On Best Taste', 'Puer', '0', 'Shou', 'NULL', '0.12','25', '57');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('67', 'Liquid Proust', 'Red Jade', '2024', 'White', 'Taiwanese', 'Rub 18','0.52', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('68', 'Viet Sun', 'Cao Bo Shou', '2021', 'Puer', 'Vietnamese', 'NULL','0.15', '12');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('69', 'Puerh Junky', 'MKRS Da Xue Shan', '2009', 'Puer', 'Aged Sheng', 'NSV','0.18', '12');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('70', 'Old Ways Tea', 'Jin Jun Mei', '2024', 'Black', 'Wuyi', 'Jin Jun Mei','0.82', '15');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('71', 'Bitterleaf', 'Goddess Roast Tie Guan Yin', '2013', 'Oolong', 'Anxi', 'Tie Guan Yin','0.21', '50');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('72', 'Song Tea', 'The Chens New Garden Medium Roast', '2021', 'Oolong', 'Taiwanese', 'NULL','1.1', '8');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('73', 'Cookie Counselor', 'Puer', '2015', 'Shou', 'NULL', '0.28','25', '60');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('74', 'Morning Crane', 'Jeong Jae Yoon Halmonicha', '2023', 'Balhyocha', 'Korean', 'NULL','0.4', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('75', 'Floating Leaves', 'Dark Roast Tie Guan Yin', '2023', 'Oolong', 'Taiwanese', 'Tie Guan Yin','0.30', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('76', 'Thes du Japon', 'Sayama, Hokumei', '2023', 'Green', 'Sencha', 'Hokumei','0.22', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('77', 'Old Ways Tea', 'Handmade Rou Gui', '2022', 'Oolong', 'Wuyi', 'Rou Gui','0.6', '8');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('78', 'Old Ways Tea', 'Ma Ton Yan Rou Gui', '2022', 'Oolong', 'Wuyi', 'Rou Gui','1.32', '8');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('79', 'Old Ways Tea', 'Old Tree Rou Gui', '2024', 'Oolong', 'Wuyi', 'Rou Gui','0.56', '40');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('80', 'Old Ways Tea', 'New Tree Rou Gui', '2024', 'Oolong', 'Wuyi', 'Rou Gui','0.32', '40');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('81', 'Ippodo', 'Seiun/Shoin', '2024', 'Green', 'Matcha', 'Blend','0.68', '30');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('82', 'Old Ways Tea', 'Cousins Fo Shou', '2022', 'Oolong', 'Wuyi', 'Fo Shou','0.22', '40');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('83', 'Yee On', 'Purple Mark', '2009', 'Puer', 'Shou', 'Blend','0.08', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('84', 'Bitterleaf', 'Double Scoop Dancong', '2023', 'Oolong', 'Fenghuang', 'Yashi Xiang','0.25', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('85', 'One River Tea', 'Bi Luo Chun', '2024', 'Green', 'Chinese', 'Bi Luo Chun','0.46', '12');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('86', 'Viet Sun', 'Lai Chau Deep Forest White', '2024', 'White', 'Vietnamese', 'NSV','0.29', '100');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('87', 'Farmer Leaf', 'Baka', '2021', 'Puer', 'Young Sheng', 'NULL','0.50', '10');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('88', 'Bitterleaf', 'Future Sailor', '2022', 'White', 'NULL', 'NSV','0.24', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('89', 'Kettl', 'Zairai Heirloom Hand Roast Hojicha', '2022', 'Green', 'Hojicha', 'Zarai','.56', '10');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('90', 'Uji-cha-en', 'Chiran Fukamushi', '2024', 'Green', 'Sencha', 'Blend','0.14', '20');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('91', 'Ketlee', 'Nilgiri Candy Black', '2023', 'Black', 'Nilgiri', 'NULL','0.30', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('92', 'Song Tea', 'Classic Rougui', '2021', 'Oolong', 'Wuyi', 'Rou Gui','1.2', '8');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('93', 'Ryuouen', 'Jou Yanagi Hojicha', '0', 'Green', 'Hojicha', 'NULL','0.13', '10');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('94', 'Thes du Japon', 'Yoneta Goko Gyokuro', '2023', 'Green', 'Gyokuro', 'Goko','0.70', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('95', 'Viet Sun', 'Lao Cai Black', '2024', 'Black', 'Vietnamese', 'NSV','0.19', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('96', 'One River Tea', 'Golden Green', '2024', 'Green', 'CN Green', '0.34','12', '64');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('97', 'Viet Sun', 'Lung Vai', '2024', 'White', 'Vietnamese', 'NSV','0.21', '20');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('98', 'Farmer Leaf', 'Ba Da Ye', '2022', 'Puer', 'Young Sheng', 'Jinggu','0.13', '10');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('99', 'Viet Sun', 'Lao Cai Secret Forest Black', '2024', 'Black', 'Vietnamese', 'NSV','0.25', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('100', 'Ryuouen', 'Kin Hojicha', '0', 'Green', 'Hojicha', 'NULL','0.38', '10');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('101', 'Puerh Junky', 'CNNP Water Blue Mark', '2007', 'Puer', 'Aged Sheng', 'Blend','0.17', '12');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('102', 'Floating Leaves', 'GABA Oolong', '2023', 'Oolong', 'Taiwanese', 'Qing Xin','0.35', '30');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('103', 'Ketlee', 'Assam Autumn Gold', '2023', 'Black', 'Indian', 'Assam','0.52', '10');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('104', 'One River Tea', 'Enshi Yulu', '2024', 'Green', 'Enshi', 'Yulu','0.42', '12');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('105', 'Thes du Japon', 'Okukuji Yabukita', '2023', 'Green', 'Sencha', 'Yabukita','0.20', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('106', 'Thes du Japon', 'Mimasaka Ryofu', '2023', 'Green', 'Sencha', 'Ryofu','0.15', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('107', 'Bitterleaf', 'In the Rough Songzhong Dancong', '2023', 'Oolong', 'Fenghuang', 'Songzhong','0.63', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('108', 'Ketlee', 'Nilgiri Needle Green', '2024', 'Green', 'Indian', 'NULL','0.13', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('109', 'Ketlee', 'Nilgiri Highland Oolong', '2023', 'Oolong', 'Indian', 'NULL','0.54', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('110', 'Yunnan Sourcing', 'Wild Tree Purple Moonlight White from Jinggu', '2023', 'White', 'Jinggu', 'NSV','0.28', '15');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('111', 'Mountain Stream Teas', 'Coastal Mountain Deep Water', '2023', 'Oolong', 'Taiwanese', 'Jin Xuan','0.24', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('112', 'White2Tea', 'Yesheng Gushu Baicha', '2022', 'White', 'NULL', 'NSV','0.46', '20');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('113', 'White2Tea', 'Charing Cross', '2023', 'White', 'NULL', 'NULL','0.42', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('114', 'White2Tea', 'Gongmei', '2013', 'White', 'NULL', 'NULL','0.32', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('115', 'White2Tea', 'Shoumei', '2014', 'White', 'NULL', 'NULL','0.13', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('116', 'White2Tea', 'Yanhong', '2023', 'Black', 'Yunnan', 'NULL','0.12', '15');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('117', 'White2Tea', 'Tiltshift', '2021', 'White', 'NULL', 'NULL','0.16', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('118', 'Old Ways Tea', 'Friends Fo Shou', '2022', 'Oolong', 'Wuyi', 'Fo Shou','0.21', '40');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('119', 'Yunnan Sourcing', 'Black Gold Bi Luo Chun', '2023', 'Black', 'Yunnan', 'NULL','0.12', '40');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('120', 'Viet Sun', 'Son La Wild Tree', '2023', 'Puerh', 'Young Sheng', 'NSV','0.28', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('121', 'Viet Sun', 'Sunset Oolong', '2023', 'Oolong', 'Vietnamese', 'Assam','0.35', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('122', 'Ketlee', 'Nilgiri Candy Oolong', '2023', 'Oolong', 'Nilgiri', 'NULL','0.30', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('123', 'Essence of Tea', 'Boundless', '2021', 'Puer', 'Young Sheng', 'Gushu','0.44', '10');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('124', 'Puerh Junky', 'CNNP Thick Zen', '2007', 'Puer', 'Aged Sheng', 'NULL','0.16', '12');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('125', 'Bitterleaf', 'Forest Echo Zhilan Xiang', '2023', 'Oolong', 'Fenghuang', 'Zhilan Xiang','0.22', '12');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('126', 'Puerh Junky', 'CNNP Fuhai 7536 "Mincemeat"', '2007', 'Puer', 'Aged Sheng', 'Blend','0.11', '12');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('127', 'Old Ways Tea', 'Aged Shui Xian', '2015', 'Oolong', 'Wuyi', 'Shui Xian','0.20', '40');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('128', 'Old Ways Tea', 'Aged Qi Dan', '2013', 'Oolong', 'Wuyi', 'Qi Dan','0.29', '40');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('129', 'Yunnan Sourcing', 'Purple Needle Black Tea of Jing Mai Mountain', '2023', 'Black', 'NULL', 'NSV','0.11', '20');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('130', 'Puerh Junky', 'CNNP Bulang Peacock', '2014', 'Puer', 'Aged Sheng', 'Bulang','0.18', '12');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('131', 'White2Tea', '941', '2023', 'Puer', 'Young Sheng', 'Yiwu','0.14', '8');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('132', 'Old Ways Tea', 'Huang Guan Yin Batch #1', '2024', 'Oolong', 'Wuyi', 'Huang Guan Yin','0.25', '40');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('133', 'Old Ways Tea', 'Huang Guan Yin Batch #2', '2024', 'Oolong', 'Wuyi', 'Huang Guan Yin','0.25', '40');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('134', 'Bitterleaf', 'Easy Breezy Duck Shit', '2023', 'Oolong', 'Fenghuang', 'Yashi Xiang','0.27', '25');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('135', 'White2Tea', 'Zhenghe Red', '2023', 'Black', 'NULL', 'NULL','0.11', '10');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('136', 'Bitterleaf', 'Oh Deer', '2022', 'Puer', 'Young Sheng', 'NULL','0.29', '8');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('137', 'White2Tea', 'Veldt', '2023', 'Puer', 'Young Sheng', 'NULL','0.17', '8');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('138', 'Jade Leaf', 'Xiaguan Love Forever Paper Tong', '2013', 'Puer', 'Aged Sheng', 'NULL','0.40', '10');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('139', 'Liquid Proust', 'Whipped Lemon Purple Sheng', '2018', 'Puer', 'Young Sheng', 'NSV','1.25', '12');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('140', 'Bitterleaf', 'Plum Beauty', '2023', 'Puer', 'Young Sheng', 'NULL','0.23', '10');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('141', 'Bitterleaf', 'Pain & Pleasure', '2023', 'Puer', 'Young Sheng', 'NULL','0.55', '10');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('142', 'Bitterleaf', 'Year of the Bull', '2022', 'Puer', 'Young Sheng', 'Yiwu','0.11', '10');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('143', 'Mountain Stream Teas', 'Nanhu Mountain', '2024', 'Oolong', 'Taiwanese', 'NULL','0.36', '10');
INSERT INTO teas(rank, vendor, name, year, type, subtype, cultivar, cost, amount) VALUES ('144', 'Mountain Stream Teas', 'Snow Pick Chi Lai', '2024', 'Oolong', 'Taiwanese', 'Qing Xin','0.32', '10');
